# Generated by Django 5.2.15 on 2026-06-16 17:18

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ListaEnvio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=120, verbose_name='Nome da lista')),
                ('criada_em', models.DateTimeField(default=django.utils.timezone.now)),
                ('ativa', models.BooleanField(default=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listas_envio', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Lista de envio',
                'verbose_name_plural': 'Listas de envio',
                'ordering': ['-criada_em'],
            },
        ),
        migrations.CreateModel(
            name='Disparo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mensagem', models.TextField()),
                ('status', models.CharField(choices=[('RASCUNHO', 'Rascunho'), ('SIMULADO', 'Simulado'), ('ENVIADO', 'Enviado'), ('ERRO', 'Erro')], default='SIMULADO', max_length=20)),
                ('total_contatos', models.PositiveIntegerField(default=0)),
                ('criado_em', models.DateTimeField(default=django.utils.timezone.now)),
                ('enviado_em', models.DateTimeField(blank=True, null=True)),
                ('retorno_api', models.TextField(blank=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disparos', to=settings.AUTH_USER_MODEL)),
                ('lista', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='disparos', to='core.listaenvio')),
            ],
            options={
                'verbose_name': 'Disparo',
                'verbose_name_plural': 'Disparos',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='ContatoLista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(blank=True, max_length=120)),
                ('telefone', models.CharField(max_length=20)),
                ('observacao', models.CharField(blank=True, max_length=255)),
                ('criado_em', models.DateTimeField(default=django.utils.timezone.now)),
                ('lista', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contatos', to='core.listaenvio')),
            ],
            options={
                'verbose_name': 'Contato da lista',
                'verbose_name_plural': 'Contatos da lista',
                'ordering': ['nome', 'telefone'],
                'unique_together': {('lista', 'telefone')},
            },
        ),
    ]
