# Generated by Django 5.2.15 on 2026-06-19 20:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_anexos_conversa'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contatolista',
            options={},
        ),
        migrations.AlterModelOptions(
            name='conversa',
            options={},
        ),
        migrations.AlterModelOptions(
            name='disparo',
            options={},
        ),
        migrations.AlterModelOptions(
            name='listaenvio',
            options={},
        ),
        migrations.AlterModelOptions(
            name='mensagemconversa',
            options={'ordering': ['criada_em']},
        ),
        migrations.RenameField(
            model_name='disparo',
            old_name='total_contatos',
            new_name='quantidade',
        ),
        migrations.RemoveField(
            model_name='contatolista',
            name='observacao',
        ),
        migrations.RemoveField(
            model_name='disparo',
            name='enviado_em',
        ),
        migrations.RemoveField(
            model_name='disparo',
            name='retorno_api',
        ),
        migrations.RemoveField(
            model_name='listaenvio',
            name='ativa',
        ),
        migrations.RemoveField(
            model_name='listaenvio',
            name='usuario',
        ),
        migrations.RemoveField(
            model_name='mensagemconversa',
            name='retorno_api',
        ),
        migrations.AddField(
            model_name='conversa',
            name='finalizada_em',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='listaenvio',
            name='atualizada_em',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='listaenvio',
            name='criada_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='mensagemconversa',
            name='lida',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='contatolista',
            name='criado_em',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='contatolista',
            name='nome',
            field=models.CharField(blank=True, max_length=160),
        ),
        migrations.AlterField(
            model_name='contatolista',
            name='telefone',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='conversa',
            name='atualizada_em',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='conversa',
            name='criada_em',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='conversa',
            name='nome',
            field=models.CharField(blank=True, max_length=160),
        ),
        migrations.AlterField(
            model_name='conversa',
            name='responsavel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conversas_responsavel', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='conversa',
            name='telefone',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='disparo',
            name='criado_em',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='disparo',
            name='lista',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.listaenvio'),
        ),
        migrations.AlterField(
            model_name='disparo',
            name='status',
            field=models.CharField(choices=[('SIMULADO', 'Simulado'), ('ENVIADO', 'Enviado'), ('ERRO', 'Erro')], default='SIMULADO', max_length=20),
        ),
        migrations.AlterField(
            model_name='disparo',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='listaenvio',
            name='criada_em',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='listaenvio',
            name='nome',
            field=models.CharField(max_length=160),
        ),
        migrations.AlterField(
            model_name='mensagemconversa',
            name='arquivo',
            field=models.FileField(blank=True, null=True, upload_to='chat_uploads/%Y/%m/'),
        ),
        migrations.AlterField(
            model_name='mensagemconversa',
            name='direcao',
            field=models.CharField(choices=[('ENVIADA', 'Enviada'), ('RECEBIDA', 'Recebida')], max_length=20),
        ),
        migrations.AlterField(
            model_name='mensagemconversa',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='PerfilUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('perfil', models.CharField(choices=[('ADMIN', 'Administrador'), ('OPERADOR', 'Operador')], default='OPERADOR', max_length=20)),
                ('ativo_sistema', models.BooleanField(default=True)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil_whatsapp', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
