# Generated by Django 5.2.15 on 2026-06-22 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_perfilusuario_perfil'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversa',
            name='status',
            field=models.CharField(choices=[('ABERTA', 'Nova mensagem'), ('EM_ATENDIMENTO', 'Em atendimento'), ('AGUARDANDO', 'Aguardando retorno'), ('TRANSFERENCIA_SOLICITADA', 'Transferência solicitada'), ('FINALIZADA', 'Finalizada')], default='ABERTA', max_length=40),
        ),
    ]
