# Generated by Django 5.2.15 on 2026-06-22 21:37

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_conversa_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WhatsAppConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(default='LD Cargo', max_length=120)),
                ('numero', models.CharField(default='+55 35 3606-5528', max_length=30)),
                ('phone_number_id', models.CharField(default='11239284241451517', max_length=80)),
                ('access_token', models.TextField(blank=True)),
                ('webhook_url', models.URLField(blank=True)),
                ('webhook_verify_token', models.CharField(blank=True, max_length=120)),
                ('status', models.CharField(choices=[('AGUARDANDO_VERIFICACAO', 'Aguardando verificação'), ('CONECTADO', 'Conectado'), ('FALHA', 'Falha na conexão'), ('DESATIVADO', 'Desativado')], default='AGUARDANDO_VERIFICACAO', max_length=40)),
                ('ativo', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Configuração WhatsApp API',
                'verbose_name_plural': 'Configurações WhatsApp API',
            },
        ),
        migrations.AddField(
            model_name='mensagemconversa',
            name='erro_integracao',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='mensagemconversa',
            name='meta_message_id',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='mensagemconversa',
            name='status_entrega',
            field=models.CharField(choices=[('SIMULADA', 'Simulada'), ('FILA', 'Na fila'), ('ENVIANDO', 'Enviando'), ('ENVIADA', 'Enviada'), ('ENTREGUE', 'Entregue'), ('LIDA', 'Lida'), ('FALHA', 'Falha no envio')], default='SIMULADA', max_length=20),
        ),
        migrations.CreateModel(
            name='WhatsAppIntegrationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('evento', models.CharField(choices=[('CONFIG', 'Configuração'), ('TESTE', 'Teste de conexão'), ('ENVIO', 'Envio'), ('RECEBIMENTO', 'Recebimento'), ('WEBHOOK', 'Webhook'), ('ERRO', 'Erro')], max_length=30)),
                ('status', models.CharField(choices=[('SIMULADO', 'Simulado'), ('SUCESSO', 'Sucesso'), ('FALHA', 'Falha'), ('PENDENTE', 'Pendente')], default='SIMULADO', max_length=20)),
                ('destino', models.CharField(blank=True, max_length=30)),
                ('resumo', models.CharField(blank=True, max_length=255)),
                ('payload', models.TextField(blank=True)),
                ('resposta', models.TextField(blank=True)),
                ('criado_em', models.DateTimeField(default=django.utils.timezone.now)),
                ('config', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logs', to='core.whatsappconfig')),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Log de integração WhatsApp',
                'verbose_name_plural': 'Logs de integração WhatsApp',
                'ordering': ['-criado_em'],
            },
        ),
    ]
